// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCShop.Data;

#nullable disable

namespace PCShop.Data.Migrations
{
    [DbContext(typeof(PCShopDbContext))]
    [Migration("20250707202814_InitialSeedDb")]
    partial class InitialSeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PCShop.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Full address of the user");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("City where the user resides");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("Full name of the user");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the user is deleted");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("State or region where the user resides");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasComment("Represents a user in the PC Shop system");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("df1c3a0f-1234-4cde-bb55-d5f15a6aabcd"),
                            AccessFailedCount = 0,
                            Address = "123 Admin Street",
                            City = "Admin City",
                            ConcurrencyStamp = "d021a7e6-ab5b-452c-8f0e-9aa363c19e48",
                            Email = "admin@pcshop.com",
                            EmailConfirmed = true,
                            FullName = "Admin User",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PCSHOP.COM",
                            NormalizedUserName = "ADMIN@PCSHOP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELeYEnzn9cElK/GbOVEO+vjZ7jb2uhHl9gepiCJBCziS0TV4gMIxPvOPOmsPMkuxXA==",
                            PhoneNumberConfirmed = false,
                            PostalCode = "00000",
                            SecurityStamp = "d9568473-201c-4a30-89b0-27b90726a580",
                            TwoFactorEnabled = false,
                            UserName = "admin@pcshop.com"
                        });
                });

            modelBuilder.Entity("PCShop.Data.Models.Computer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the computer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Description of the computer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Image URL for the computer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the computer is deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the computer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the computer in decimal format");

                    b.HasKey("Id");

                    b.ToTable("Computers", t =>
                        {
                            t.HasComment("Represents a computer in the PC Shop system");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1f11111-aaaa-bbbb-cccc-111111111111"),
                            Description = "CPU: AMD Ryzen 5 5600, GPU: GeForce RTX 3060TI, RAM: 32GB DDR4, Storage: 1TB SSD NVMe...",
                            ImageUrl = "images/computers/grigs_polaris_max_amd.png",
                            IsDeleted = false,
                            Name = "G:RIGS POLARIS Max (AMD)",
                            Price = 2000.00m
                        },
                        new
                        {
                            Id = new Guid("f2f22222-aaaa-bbbb-cccc-222222222222"),
                            Description = "CPU: Intel Core i5-13400F, GPU: GeForce RTX 3060TI, RAM: 32GB DDR4, Storage: 1TB SSD NVMe...",
                            ImageUrl = "images/computers/grigs_polaris_max_intel.png",
                            IsDeleted = false,
                            Name = "G:RIGS POLARIS Max (Intel)",
                            Price = 2100.00m
                        },
                        new
                        {
                            Id = new Guid("f3f33333-aaaa-bbbb-cccc-333333333333"),
                            Description = "CPU: AMD Ryzen 7 5700X3D, GPU: GeForce RTX 4060, RAM: 32GB DDR5, Storage: 2TB SSD NVMe...",
                            ImageUrl = "images/computers/grigs_spark_ultra_amd_x3d.png",
                            IsDeleted = false,
                            Name = "G:RIGS SPARK Ultra (AMD X3D)",
                            Price = 2500.00m
                        },
                        new
                        {
                            Id = new Guid("f4f44444-aaaa-bbbb-cccc-444444444444"),
                            Description = "CPU: Intel Core i5-14600KF, GPU: GeForce RTX 5070, RAM: 32GB DDR5, Storage: 2TB SSD NVMe...",
                            ImageUrl = "images/computers/grigs_nova_ultra_intel.png",
                            IsDeleted = false,
                            Name = "G:RIGS NOVA Ultra (Intel)",
                            Price = 3690.00m
                        },
                        new
                        {
                            Id = new Guid("f5f55555-aaaa-bbbb-cccc-555555555555"),
                            Description = "CPU: AMD Ryzen 7 7700, GPU: GeForce RTX 5070, RAM: 32GB DDR5, Storage: 2TB SSD NVMe...",
                            ImageUrl = "images/computers/grigs_sirius_ultra_amd_zen4_wh.png",
                            IsDeleted = false,
                            Name = "G:RIGS SIRIUS Ultra (AMD Zen4)",
                            Price = 4200.00m
                        },
                        new
                        {
                            Id = new Guid("f6f66666-aaaa-bbbb-cccc-666666666666"),
                            Description = "CPU: Intel Core i7-13700K, GPU: GeForce RTX 4070, RAM: 32GB DDR5, Storage: 2TB SSD NVMe...",
                            ImageUrl = "images/computers/grigs_sirius_ultra_intel.png",
                            IsDeleted = false,
                            Name = "G:RIGS SIRIUS Ultra (Intel)",
                            Price = 4500.00m
                        });
                });

            modelBuilder.Entity("PCShop.Data.Models.ComputerPart", b =>
                {
                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Computer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Product");

                    b.HasKey("ComputerId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ComputersParts", t =>
                        {
                            t.HasComment("Represents a part of a computer, linking it to a specific product");
                        });
                });

            modelBuilder.Entity("PCShop.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the order");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced AspNetUser");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("The date and time when the order was placed");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("The current status of the order");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The total price of the order, including all items and taxes");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("Represents an order placed by a user in the system");
                        });
                });

            modelBuilder.Entity("PCShop.Data.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Order");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced Product");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrdersItems", t =>
                        {
                            t.HasComment("Represents an item in an order, linking a product to an order");
                        });
                });

            modelBuilder.Entity("PCShop.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the product");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Description of the product");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Image URL for the product");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the product is deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the product");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the product in decimal format");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to the referenced ProductType");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("Represents a product in the PC Shop system");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-aaaa-bbbb-cccc-101010101010"),
                            Description = "13th Gen 16-core processor with high performance for gaming and productivity.",
                            ImageUrl = "/images/products/intel-i7-13700k.jpg",
                            IsDeleted = false,
                            Name = "Intel Core i7-13700K",
                            Price = 489.99m,
                            ProductTypeId = new Guid("11111111-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20202020-aaaa-bbbb-cccc-202020202020"),
                            Description = "Latest generation graphics card with ray tracing and DLSS support.",
                            ImageUrl = "/images/products/rtx-4070.jpg",
                            IsDeleted = false,
                            Name = "NVIDIA GeForce RTX 4070",
                            Price = 629.00m,
                            ProductTypeId = new Guid("22222222-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("30303030-aaaa-bbbb-cccc-303030303030"),
                            Description = "High-performance DDR4 memory kit with RGB lighting.",
                            ImageUrl = "/images/products/corsair-vengeance-32gb.jpg",
                            IsDeleted = false,
                            Name = "Corsair Vengeance RGB Pro 32GB DDR4",
                            Price = 139.99m,
                            ProductTypeId = new Guid("44444444-aaaa-bbbb-cccc-444444444444")
                        },
                        new
                        {
                            Id = new Guid("40404040-aaaa-bbbb-cccc-404040404040"),
                            Description = "Ultra-fast PCIe 4.0 SSD ideal for gaming and heavy applications.",
                            ImageUrl = "/images/products/samsung-980-pro.jpg",
                            IsDeleted = false,
                            Name = "Samsung 980 PRO 1TB NVMe SSD",
                            Price = 119.49m,
                            ProductTypeId = new Guid("55555555-aaaa-bbbb-cccc-555555555555")
                        },
                        new
                        {
                            Id = new Guid("50505050-aaaa-bbbb-cccc-505050505050"),
                            Description = "Premium Z790 chipset motherboard supporting 13th Gen Intel CPUs.",
                            ImageUrl = "/images/products/asus-z790.jpg",
                            IsDeleted = false,
                            Name = "ASUS ROG STRIX Z790-E",
                            Price = 379.00m,
                            ProductTypeId = new Guid("33333333-aaaa-bbbb-cccc-333333333333")
                        },
                        new
                        {
                            Id = new Guid("60606060-aaaa-bbbb-cccc-606060606060"),
                            Description = "Reliable and efficient 750W power supply unit with modular cables.",
                            ImageUrl = "/images/products/cooler-master-750w.jpg",
                            IsDeleted = false,
                            Name = "Cooler Master 750W 80+ Gold PSU",
                            Price = 109.99m,
                            ProductTypeId = new Guid("77777777-aaaa-bbbb-cccc-777777777777")
                        });
                });

            modelBuilder.Entity("PCShop.Data.Models.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the product type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of the product type");

                    b.HasKey("Id");

                    b.ToTable("ProductsTypes", t =>
                        {
                            t.HasComment("Product type of the PC Shop system");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            Name = "Processor"
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-bbbb-cccc-222222222222"),
                            Name = "Video Card"
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-bbbb-cccc-333333333333"),
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-bbbb-cccc-444444444444"),
                            Name = "RAM"
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-bbbb-cccc-555555555555"),
                            Name = "SSD"
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-bbbb-cccc-666666666666"),
                            Name = "HDD"
                        },
                        new
                        {
                            Id = new Guid("77777777-aaaa-bbbb-cccc-777777777777"),
                            Name = "Power Supply"
                        },
                        new
                        {
                            Id = new Guid("88888888-aaaa-bbbb-cccc-888888888888"),
                            Name = "Cooling System"
                        },
                        new
                        {
                            Id = new Guid("99999999-aaaa-bbbb-cccc-999999999999"),
                            Name = "Case Fan"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa1-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Case"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa2-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa3-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa4-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa5-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Headset"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa6-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Mousepad"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa7-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Speakers"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa8-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Microphone"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa9-aaaa-bbbb-cccc-aaaaaaaaaaaa"),
                            Name = "Webcam"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PCShop.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PCShop.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PCShop.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PCShop.Data.Models.ComputerPart", b =>
                {
                    b.HasOne("PCShop.Data.Models.Computer", "Computer")
                        .WithMany("ComputersParts")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCShop.Data.Models.Product", "Product")
                        .WithMany("ComputersParts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PCShop.Data.Models.Order", b =>
                {
                    b.HasOne("PCShop.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PCShop.Data.Models.OrderItem", b =>
                {
                    b.HasOne("PCShop.Data.Models.Order", "Order")
                        .WithMany("OrdersItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCShop.Data.Models.Product", "Product")
                        .WithMany("OrdersItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PCShop.Data.Models.Product", b =>
                {
                    b.HasOne("PCShop.Data.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("PCShop.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PCShop.Data.Models.Computer", b =>
                {
                    b.Navigation("ComputersParts");
                });

            modelBuilder.Entity("PCShop.Data.Models.Order", b =>
                {
                    b.Navigation("OrdersItems");
                });

            modelBuilder.Entity("PCShop.Data.Models.Product", b =>
                {
                    b.Navigation("ComputersParts");

                    b.Navigation("OrdersItems");
                });

            modelBuilder.Entity("PCShop.Data.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
